<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AzCopyAndDelete</RootNamespace>
    <AssemblyName>AzCopyAndDelete</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
  </ItemGroup>
</Project>
